# Generated by Django 4.2.3 on 2023-08-15 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addTask', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addtask',
            name='id',
        ),
        migrations.AlterField(
            model_name='addtask',
            name='dueDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='addtask',
            name='task_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
