# Generated by Django 4.2.3 on 2023-08-17 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
