# Generated by Django 4.2.3 on 2023-08-24 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('assigned', models.CharField(max_length=100)),
                ('dueDate', models.DateField()),
                ('prio', models.CharField(max_length=100)),
                ('status', models.CharField(default='todo', max_length=100)),
            ],
        ),
    ]
